*** Starting uWSGI 2.0.19.1 (64bit) on [Thu Jun 24 11:39:03 2021] ***
compiled with version: Apple LLVM 12.0.0 (clang-1200.0.32.21) on 24 June 2021 02:18:18
os: Darwin-20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
nodename: llshdeMacBook-Pro.local
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /Users/llsh/PycharmProjects/pythonProject/dataAnalysis/dataAnalysis
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /Users/llsh/PycharmProjects/pythonProject/dataAnalysis
your processes number limit is 2784
your memory page size is 4096 bytes
detected max file descriptor number: 256
lock engine: OSX spinlocks
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:62757 (port auto-assigned) fd 3
Python version: 3.9.5 (default, May  4 2021, 03:36:27)  [Clang 12.0.0 (clang-1200.0.32.29)]
Python main interpreter initialized at 0x7fb39c509970
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416640 bytes (406 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
Traceback (most recent call last):
  File "dataAnalysis/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 63761)
spawned uWSGI worker 1 (pid: 63766, cores: 2)
spawned uWSGI worker 2 (pid: 63767, cores: 2)
spawned uWSGI worker 3 (pid: 63768, cores: 2)
spawned uWSGI worker 4 (pid: 63769, cores: 2)
spawned uWSGI http 1 (pid: 63770)
--- no python application found, check your startup logs for errors ---
[uwsgi-http key: 127.0.0.1:8000 client_addr: 127.0.0.1 client_port: 2810] hr_instance_read(): Connection reset by peer [plugins/http/http.c line 647]
[pid: 63768|app: -1|req: -1/1] 127.0.0.1 () {34 vars in 459 bytes} [Thu Jun 24 12:57:19 2021] POST /api/apriori => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 63767|app: -1|req: -1/2] 127.0.0.1 () {34 vars in 459 bytes} [Thu Jun 24 12:58:00 2021] POST /api/apriori => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
respawned uWSGI http 1 (pid: 64104)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 64104)
worker 4 buried after 1 seconds
worker 3 buried after 1 seconds
worker 2 buried after 1 seconds
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.19.1 (64bit) on [Fri Jun 25 10:02:57 2021] ***
compiled with version: Apple LLVM 12.0.0 (clang-1200.0.32.21) on 24 June 2021 02:18:18
os: Darwin-20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
nodename: llshdeMacBook-Pro.local
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /Users/llsh/PycharmProjects/pythonProject/dataAnalysis/dataAnalysis
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /Users/llsh/PycharmProjects/pythonProject/dataAnalysis
your processes number limit is 2784
your memory page size is 4096 bytes
detected max file descriptor number: 256
lock engine: OSX spinlocks
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:55058 (port auto-assigned) fd 3
Python version: 3.9.5 (default, May  4 2021, 03:36:27)  [Clang 12.0.0 (clang-1200.0.32.29)]
Python main interpreter initialized at 0x7faa3e508190
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416640 bytes (406 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
Traceback (most recent call last):
  File "dataAnalysis/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 64646)
spawned uWSGI worker 1 (pid: 64662, cores: 2)
spawned uWSGI worker 2 (pid: 64663, cores: 2)
spawned uWSGI worker 3 (pid: 64664, cores: 2)
spawned uWSGI worker 4 (pid: 64665, cores: 2)
spawned uWSGI http 1 (pid: 64666)
--- no python application found, check your startup logs for errors ---
[pid: 64664|app: -1|req: -1/1] 127.0.0.1 () {38 vars in 518 bytes} [Fri Jun 25 10:03:18 2021] POST /api/apriori => generated 21 bytes in 1 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 64666)
worker 4 buried after 1 seconds
worker 3 buried after 1 seconds
worker 2 buried after 1 seconds
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.19.1 (64bit) on [Fri Jun 25 10:08:23 2021] ***
compiled with version: Apple LLVM 12.0.0 (clang-1200.0.32.21) on 24 June 2021 02:18:18
os: Darwin-20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
nodename: llshdeMacBook-Pro.local
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /Users/llsh/PycharmProjects/pythonProject/dataAnalysis/dataAnalysis
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /Users/llsh/PycharmProjects/pythonProject/dataAnalysis
your processes number limit is 2784
your memory page size is 4096 bytes
detected max file descriptor number: 256
lock engine: OSX spinlocks
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:55112 (port auto-assigned) fd 3
Python version: 3.9.5 (default, May  4 2021, 03:36:27)  [Clang 12.0.0 (clang-1200.0.32.29)]
Python main interpreter initialized at 0x7fa45be09f80
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416640 bytes (406 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
Traceback (most recent call last):
  File "dataAnalysis/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/django/apps/config.py", line 224, in create
    import_module(entry)
  File "/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rest_framework'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 64759)
spawned uWSGI worker 1 (pid: 64775, cores: 2)
spawned uWSGI worker 2 (pid: 64776, cores: 2)
spawned uWSGI worker 3 (pid: 64777, cores: 2)
spawned uWSGI worker 4 (pid: 64778, cores: 2)
spawned uWSGI http 1 (pid: 64779)
--- no python application found, check your startup logs for errors ---
[pid: 64777|app: -1|req: -1/1] 127.0.0.1 () {38 vars in 519 bytes} [Fri Jun 25 02:08:28 2021] POST /api/apriori => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 64779)
worker 4 buried after 1 seconds
worker 3 buried after 1 seconds
worker 2 buried after 1 seconds
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.19.1 (64bit) on [Fri Jun 25 10:10:12 2021] ***
compiled with version: Apple LLVM 12.0.0 (clang-1200.0.32.21) on 24 June 2021 02:18:18
os: Darwin-20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
nodename: llshdeMacBook-Pro.local
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /Users/llsh/PycharmProjects/pythonProject/dataAnalysis/dataAnalysis
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /Users/llsh/PycharmProjects/pythonProject/dataAnalysis
your processes number limit is 2784
your memory page size is 4096 bytes
detected max file descriptor number: 256
lock engine: OSX spinlocks
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:55281 (port auto-assigned) fd 3
Python version: 3.9.5 (default, May  4 2021, 03:36:27)  [Clang 12.0.0 (clang-1200.0.32.29)]
Python main interpreter initialized at 0x7fb4ee7062f0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416640 bytes (406 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7fb4ee7062f0 pid: 64838 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 64838)
spawned uWSGI worker 1 (pid: 64854, cores: 2)
spawned uWSGI worker 2 (pid: 64855, cores: 2)
spawned uWSGI worker 3 (pid: 64856, cores: 2)
spawned uWSGI worker 4 (pid: 64857, cores: 2)
spawned uWSGI http 1 (pid: 64858)
Internal Server Error: /api/apriori
Traceback (most recent call last):
  File "/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 116, in __call__
    response = self.process_request(request)
  File "/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 53, in process_request
    if self.should_redirect_with_slash(request):
  File "/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 70, in should_redirect_with_slash
    if not is_valid_path(request.path_info, urlconf):
  File "/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/django/urls/base.py", line 153, in is_valid_path
    return resolve(path, urlconf)
  File "/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/llsh/PycharmProjects/pythonProject/dataAnalysis/./dataAnalysis/urls.py", line 16, in <module>
    from algorithm import views
  File "/Users/llsh/PycharmProjects/pythonProject/dataAnalysis/./algorithm/views.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[pid: 64856|app: 0|req: 1/1] 127.0.0.1 () {38 vars in 519 bytes} [Fri Jun 25 02:10:15 2021] POST /api/apriori => generated 129286 bytes in 150 msecs (HTTP/1.1 500) 3 headers in 126 bytes (2 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 64858)
worker 4 buried after 1 seconds
worker 3 buried after 1 seconds
worker 2 buried after 1 seconds
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.19.1 (64bit) on [Fri Jun 25 10:11:23 2021] ***
compiled with version: Apple LLVM 12.0.0 (clang-1200.0.32.21) on 24 June 2021 02:18:18
os: Darwin-20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
nodename: llshdeMacBook-Pro.local
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /Users/llsh/PycharmProjects/pythonProject/dataAnalysis/dataAnalysis
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /Users/llsh/PycharmProjects/pythonProject/dataAnalysis
your processes number limit is 2784
your memory page size is 4096 bytes
detected max file descriptor number: 256
lock engine: OSX spinlocks
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:55323 (port auto-assigned) fd 3
Python version: 3.9.5 (default, May  4 2021, 03:36:27)  [Clang 12.0.0 (clang-1200.0.32.29)]
Python main interpreter initialized at 0x7fcd82505950
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416640 bytes (406 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7fcd82505950 pid: 64899 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 64899)
spawned uWSGI worker 1 (pid: 64915, cores: 2)
spawned uWSGI worker 2 (pid: 64916, cores: 2)
spawned uWSGI worker 3 (pid: 64917, cores: 2)
spawned uWSGI worker 4 (pid: 64918, cores: 2)
spawned uWSGI http 1 (pid: 64919)
农贸市场 --> 蔬菜 conf: 0.37984496124031003
超市 --> 蔬菜 conf: 0.3939393939393939
蔬菜 --> 超市 conf: 0.4431818181818182
水产品 --> 超市 conf: 0.44029850746268656
[pid: 64918|app: 0|req: 1/1] 127.0.0.1 () {38 vars in 518 bytes} [Fri Jun 25 02:11:26 2021] POST /api/apriori => generated 332 bytes in 26330 msecs (HTTP/1.1 200) 7 headers in 202 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 64919)
worker 4 buried after 1 seconds
worker 3 buried after 1 seconds
worker 2 buried after 1 seconds
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.19.1 (64bit) on [Fri Jun 25 10:13:20 2021] ***
compiled with version: Apple LLVM 12.0.0 (clang-1200.0.32.21) on 24 June 2021 02:18:18
os: Darwin-20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
nodename: llshdeMacBook-Pro.local
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /Users/llsh/PycharmProjects/pythonProject/dataAnalysis/dataAnalysis
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /Users/llsh/PycharmProjects/pythonProject/dataAnalysis
your processes number limit is 2784
your memory page size is 4096 bytes
detected max file descriptor number: 256
lock engine: OSX spinlocks
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:55353 (port auto-assigned) fd 3
Python version: 3.9.5 (default, May  4 2021, 03:36:27)  [Clang 12.0.0 (clang-1200.0.32.29)]
Python main interpreter initialized at 0x7feca7f06030
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416640 bytes (406 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7feca7f06030 pid: 64969 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 64969)
spawned uWSGI worker 1 (pid: 64985, cores: 2)
spawned uWSGI worker 2 (pid: 64986, cores: 2)
spawned uWSGI worker 3 (pid: 64987, cores: 2)
spawned uWSGI worker 4 (pid: 64988, cores: 2)
spawned uWSGI http 1 (pid: 64989)
农贸市场 --> 蔬菜 conf: 0.37984496124031003
超市 --> 蔬菜 conf: 0.3939393939393939
蔬菜 --> 超市 conf: 0.4431818181818182
水产品 --> 超市 conf: 0.44029850746268656
[pid: 64987|app: 0|req: 1/1] 127.0.0.1 () {38 vars in 519 bytes} [Fri Jun 25 02:13:24 2021] POST /api/apriori => generated 332 bytes in 832 msecs (HTTP/1.1 200) 7 headers in 202 bytes (2 switches on core 0)
农贸市场 --> 蔬菜 conf: 0.37984496124031003
超市 --> 蔬菜 conf: 0.3939393939393939
蔬菜 --> 超市 conf: 0.4431818181818182
水产品 --> 超市 conf: 0.44029850746268656
[pid: 64988|app: 0|req: 1/2] 127.0.0.1 () {38 vars in 519 bytes} [Fri Jun 25 02:13:26 2021] POST /api/apriori => generated 332 bytes in 626 msecs (HTTP/1.1 200) 7 headers in 202 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 64989)
worker 4 buried after 1 seconds
worker 3 buried after 1 seconds
worker 2 buried after 1 seconds
worker 1 buried after 1 seconds
goodbye to uWSGI.
